spring.application.name=heritage_backend
spring.datasource.url=jdbc:mysql://localhost:3306/heritage_db
spring.datasource.username=root
spring.datasource.password=Nikki@310806

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080